// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPGP0hXgtUDytkPHijLJc1vArmFw4lERQ',
    appId: '1:14211975853:web:dc3eeef43a284e24f7d424',
    messagingSenderId: '14211975853',
    projectId: 'tinderclone-b3d5a',
    authDomain: 'tinderclone-b3d5a.firebaseapp.com',
    storageBucket: 'tinderclone-b3d5a.appspot.com',
    measurementId: 'G-LD0WQJ7GQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdzISvBfgbgt3go2A7lid4lOqq4b5tT-0',
    appId: '1:14211975853:android:b26b5bc270abf85bf7d424',
    messagingSenderId: '14211975853',
    projectId: 'tinderclone-b3d5a',
    storageBucket: 'tinderclone-b3d5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWvTgTC6O5zGih17ehVNBkxCk_TR5zAo',
    appId: '1:14211975853:ios:99c422c892d5cd87f7d424',
    messagingSenderId: '14211975853',
    projectId: 'tinderclone-b3d5a',
    storageBucket: 'tinderclone-b3d5a.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgWvTgTC6O5zGih17ehVNBkxCk_TR5zAo',
    appId: '1:14211975853:ios:99c422c892d5cd87f7d424',
    messagingSenderId: '14211975853',
    projectId: 'tinderclone-b3d5a',
    storageBucket: 'tinderclone-b3d5a.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPGP0hXgtUDytkPHijLJc1vArmFw4lERQ',
    appId: '1:14211975853:web:cc94cfda15f46166f7d424',
    messagingSenderId: '14211975853',
    projectId: 'tinderclone-b3d5a',
    authDomain: 'tinderclone-b3d5a.firebaseapp.com',
    storageBucket: 'tinderclone-b3d5a.appspot.com',
    measurementId: 'G-YX9HW928M9',
  );
}
